apiVersion: v1
kind: Service
metadata:
  name: polaris
  namespace: lakehouse
spec:
  selector:
    app: polaris
  ports:
    - name: http
      port: 8181
      targetPort: 8181
    - name: metrics
      port: 8182
      targetPort: 8182


